#
# Copyright 2020 The dNation Kubernetes Monitoring Stack Authors. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v2
name: dnation-ping
version: 0.1.9
appVersion: 0.1.6
description: dNation Ping detects network connection problems by measuring ping response times of selected servers every 15 seconds.
keywords:
- kubernetes
- ping
- grafana
- prometheus
- blackbox-exporter
home: https://www.dnation.cloud
sources:
- https://github.com/dNationCloud/ping
dependencies:
- name: prometheus
  version: "11.16.*"
  repository: https://prometheus-community.github.io/helm-charts
  condition: prometheus.enabled
- name: grafana
  version: "6.1.*"
  repository: https://grafana.github.io/helm-charts
  condition: grafana.enabled
- name: prometheus-blackbox-exporter
  version: "4.9.*"
  repository: https://prometheus-community.github.io/helm-charts
  condition: prometheus-blackbox-exporter.enabled
maintainers:
- name: dNation
  email: cloud@dnation.cloud
icon: https://cdn.ifne.eu/public/icons/dnation_ping.png
