{{- if .Values.dNation }}
{{- if .Values.dNation.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ping.dnation.cloud
  namespace: dnation-ping
spec:
  secretName: {{ .Values.dNation.certificate.secretName }}
  issuerRef:
    name: {{ .Values.dNation.certificate.issuer }}
  commonName: {{ .Values.dNation.certificate.commonName }}
  dnsNames:
  {{- range .Values.dNation.certificate.hosts }}
  - {{ . }}
  {{- end }}
{{- end }}
{{- end }}
