{{- if .Values.dNation }}
{{- if .Values.dNation.certificate.enabled }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ping.dnation.cloud
spec:
  secretName: {{ .Values.dNation.certificate.secretName }}
  issuerRef:
    name: {{ .Values.dNation.certificate.issuer }}
  commonName: {{ .Values.dNation.certificate.commonName }}
  dnsNames:
  {{- range .Values.dNation.certificate.hosts }}
  - {{ . }}
  {{- end }}
{{- end }}
{{- end }}
