variables:
  # When using DinD service, we need to instruct docker, to talk with
  # the daemon started inside of the service. The daemon is available
  # with a network connection instead of the default /var/run/docker.sock socket.
  DOCKER_HOST: "tcp://docker:2375"

.base:
  image: dtzar/helm-kubectl:3.3.1
  tags:
    - docker
    - privileged
  only:
    - merge_requests
    - master

.test-install:
  extends: .base
  before_script:
    # Install KinD
    - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.8.1/kind-linux-amd64
    - chmod +x ./kind
    - mv ./kind /usr/bin/kind
    # Install Docker
    - apk add docker
    # Patch KinD config to listen on docker service's IP address
    - "sed -i 's/apiServerAddress: .*/apiServerAddress: '$(grep 'docker' /etc/hosts | awk '{print $1}')/ helpers/ping-kind-config.yaml"
  services:
    - docker:18.09-dind

stages:
  - build helm
  - test
  - publish
  - deploy

build helm package:
  stage: build helm
  extends: .base
  script:
    - helm package -u -d chart/release ./chart
  artifacts:
    paths:
    - chart/release/

test lint:
  stage: test
  extends: .base
  script:
    - helm lint ./chart -f chart/values.yaml

test install ping:
  stage: test
  extends: .test-install
  script:
    - kind create cluster --config helpers/ping-kind-config.yaml --image kindest/node:v1.17.5
    - helm install ping chart/release/dnation-ping-*.tgz

publish:
  stage: publish
  image: cfmanteiga/alpine-bash-curl-jq
  only:
    - master
  script:
    - curl --fail --user "$IFNE_HELM_USER":"$IFNE_HELM_PASS" "$IFNE_HELM_URL" --upload-file chart/release/dnation-ping-*.tgz
  when: manual

deploy:
  stage: deploy
  extends: .base
  only:
    - master
  before_script:
    # https://git.ifne.eu/infra/k8s/-/wikis/Installation-of-k8s#workaround-for-please-ensure-your-ca-certificate-and-token-are-valid-issue
    - echo "138.201.245.222 kubernetes" >> /etc/hosts
    - helm repo add dnationcloud "$IFNE_HELM_URL"
    - helm repo update
    - helm search repo dnation
  script:
    - helm upgrade --install dnation-ping dnationcloud/dnation-ping -f ./chart/values-dnation.yaml
  environment:
    name: production
    url: "$KUBE_URL"
    kubernetes:
      namespace: dnation-ping
  when: manual

